[package]
name = "ass2ass"
version = "0.1.0"
authors = ["cruelnoise <cruelnoise@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
thiserror = "1.0.22"
parse-display = "0.4.0"
num_enum = "0.5.1"
enum_default = "0.2.5"
smart-default = "0.6.0"
